# Manipulating Data using NumPy

![caption](../images/numpy-logo.jpg)
***
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. Let's along with the basics of NumPy such as its architecture and environment. It also discusses the various array functions, types of indexing, etc.

We can install numpy by `pip install numpy`

- Main object: **`ndarray`**

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

# ndarray
***

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types. An instance of ndarray class can be constructed by different array creation routines described later.

You import the function in python by calling `import numpy`. The basic ndarray is created using an array function in NumPy as follows −

In [1]:
import numpy as np


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## How do I create Arrays in Python?
***
* Create an array from a regular Python list or tuple using the array function. 

* The type of the resulting array is deduced from the type of the elements in the sequences

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [2]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

array(<class 'object'>, dtype=object)

In [5]:
a = (range(1,10))
b = [range(1,10)]
np.array(a, copy='true', dtype = int, subok = 'false', order = None, ndmin = 0)
np.array(b, copy = 'true', dtype = int, subok = 'false', order = None, ndmin = 0)
c = 'Okay'
np.array(c)

array('Okay', dtype='<U4')

In [7]:
array = np.array([1,2,3,4,5,6,7,8,9,10], ndmin = 2, copy = 'true', dtype = int, order = 'C')
print(array)

[[ 1  2  3  4  5  6  7  8  9 10]]


### Instructions
* Create a list of number's as `[10,20,30]` and save it as `my_list`
* Convert the list into an array using `np.array()`

In [8]:
my_list = [10,20,30]
np.array(my_list)


array([10, 20, 30])

### Instructions
* Create a list of list as `[[5, 10, 15], [20, 25, 30], [35, 40, 45]]` and save it as `list_of_lists `
* Convert the list of list into an array using `np.array()` and print it.
* Check the `type()` of the array.

In [9]:
list_of_lists = [[5,10,15],[20,25,30],[35,40,45]]
np.array(list_of_lists, copy = 'true', dtype = int)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

An example of how does n-dimensional looks

## Types

![NumPy Array Types](../images/numpy-types1.jpg)

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***ndarray.ndim***
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.size***
the total number of elements of the array. This is equal to the product of the elements of shape.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.

In [12]:
a =

AttributeError: 'list' object has no attribute 'shape'

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## numpy.dtype
***
<br/>
The data type or dtype describes the kind of elements that are contained within the array.

* **bool**: Boolean values
<br/><br/>

* **int**: Integer values. Can be int16, int32, or int64.


* **float**: Floating point values. Can be float16, float32, or float64.
<br/><br/>


* **string**: Text. Can be string or unicode (this distinction is greatly simplified in Python 3)

<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Let's try it ourselves!
***
### Create a vector from the list [10, 20, 30]. Print the dtype and shape.

In [13]:
okies = np.array([1,2,3], dtype = float, copy = 'true', ndmin = 1)
print(okies)

[1. 2. 3.]


<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />

### Create a matrix from the list of lists [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1, 45.6]]. Print the dtype and shape. 
***

In [23]:
b = np.array([[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1, 45.6]])
print(b.dtype)
b.shape

float64


(3, 3)

<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Indexing and Selection
***
Basic slicing extends Python's basic concept of slicing to N dimensions. Basic slicing occurs when obj is a :class: slice object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers. :const:Ellipsis and :const:newaxis objects can be interspersed with these as well. In order to remain backward compatible with a common usage in Numeric, basic slicing is also initiated if the selection object is any non-ndarray sequence (such as a :class:list) containing :class:slice objects.

Let us look at creating an array with numpy and indexing and selection follows from what we have learnt in python

### Instructions
* Create an array from `0` to `9` using `np.arange()` and save it as `arr`
* Print the element at index `5`
* Print the elements from `1` to `9` with an interval of `2`

In [24]:
# indexing one dimensional array
arr = np.arange(0,9)
print(arr[5])
print(arr[1:10:2])


5
[1 3 5 7]


### Instructions
* Create a two dimensional array from `1` to `9` and save it as `arr` and print it.
* Print 1st row
* Print the value of 2nd row and 2nd column
* Print the value of 0th row and 2nd column

In [31]:
# indexing two dimensional array
arr = np.array(range(1,10), ndmin = 2)
print(arr)
a = arr.reshape(3,3)
print(a[0])
print(a[1][1])

[[1 2 3 4 5 6 7 8 9]]
[1 2 3]
5


# Analyzing the Weather using NumPy

<center><img src="../images/weather.jpg" alt="Weather" style="width: 350px;"/></center>
Now it's time to use some them to learn data manipulation by analyzing a weather data set. As they say

We'll be working with **weather_small_2012.csv**, which contains weather data for each hour in 2012.
Since weather_small_2012.csv is a csv file, rows are separated by line breaks, and columns are
separated by commas:

```
Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27
```

**To read csv file, we use:**

    numpy.genfromtxt(fileName, delimeter=",")

### Instructions
* `weather` variable  is already defined for you with the dataset path
* Print the type of the dataset using `.dtype`
* Also print the `weather` dataset and have a look at it

In [1]:
import numpy as np
# read csv file
weather = np.genfromtxt("../data/weather_small_2012.csv", delimiter=",")
print(weather)
weather.dtype

[[   nan    nan    nan ...    nan    nan    nan]
 [   nan  -1.8   -3.9  ...   4.     8.   101.24]
 [   nan  -1.8   -3.7  ...   4.     8.   101.24]
 ...
 [   nan  -0.5   -1.5  ...  28.     4.8   99.95]
 [   nan  -0.2   -1.8  ...  28.     9.7   99.91]
 [   nan   0.    -2.1  ...  30.    11.3   99.89]]


dtype('float64')

Many items in this dataset are nan.

* The entire first row is nan – headers are String.
* Some of the numbers are written like 1.98600000e+03.

The data type of weather is float. Because all of the values in a NumPy array have to have the same
data type, NumPy attempted to convert all of the columns to floats when they were read in.

**Reading In The Data Properly**

***
To read weather_small_2012.csv file properly we will have to use correct data type and skip the header.
* genfromtxt() default dtype is float, it converts non-numeric value to nan (not a number)
* To avoid nan, we read values as |S20 (String of length 20) 

### Instructions
* Read the Weather data using `np.genfromtxt()` by passing parameters as `path of the dataset`,`dtype='|S20'`, `skip_header=1`, `delimiter=","`
* Print the value of first index of the dataset

In [51]:
weathers = np.genfromtxt("../data/weather_small_2012.csv", dtype='|S20', skip_header = 1, delimiter = ',')
weathers[0][0]

b'2012-01-01 00:00:00'

### Instructions
* Create an array of temperature and convert it into float16 using `.astype(np.float16)` and save it as `temperatures`.
* Create an array of dew point temperature and convert it into float16 using `.astype(np.float16)` and save it as `dew_point_temperatures`.


In [72]:
# Create an array of temperatures from the data set

temperatures = weathers[:,1].astype(np.float16)
dew_point_temperatures = weathers[:,2].astype(np.float16)
print(temperatures, dew_point_temperatures)
temp = (temperatures * 9/5) + 32 
print(temp)

[-1.8 -1.8 -1.8 ... -0.5 -0.2  0. ] [-3.9 -3.7 -3.4 ... -1.5 -1.8 -2.1]
[28.77 28.77 28.77 ... 31.1  31.64 32.  ]


In [73]:
ok = dew_point_temperatures[a > 30]

IndexError: too many indices for array

<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

# Operations with NumPy arrays
***
NumPy provides a lot of built-in functionality for working with arrays.
**The important concepts to remember are**
- Any operation with a scalar number or a scalar function will cause that operation being computed for each element
- Any operation with two **compatible** (eg.: same shape) arrays will cause one-to-one element computations

<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Arithmetic (1/2)
***
### Vector Arithmetic
- All operations between arrays are **element-wise**
- This means that if you multiply two 2d vectors, it will **NOT** perform matrix multiplication

<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Arithmetic (2/2)
***
### Scalar Arithmetic
- Any operation of an array with a scalar will result in **element-wise** computation of that operation
- For example **`my_array + 2`** is the same as adding 2 to each element of array

### Instructions
* Calculate the Temperatures from the weather dataset in Farenheit

In [59]:
#(12°C × 9/5) + 32 = 53.6°F
def convert(c):
    return ((c * (9 / 5)) + 32)

for i in temperatures:
    print(convert(i))

28.7603515625
28.7603515625
28.7603515625
29.3
29.3
29.479296875
29.3
29.479296875
29.479296875
29.6603515625
30.2
31.1
31.640087890625
32.359912109375
33.4396484375
35.2396484375
36.679296875
37.4
38.84140625
37.579296875
37.75859375
39.2
39.9171875
41.54140625
41.35859375
40.2828125
39.020703125
38.65859375
37.220703125
36.679296875
36.14140625
35.6
35.420703125
35.2396484375
34.7
35.95859375
35.0603515625
33.979296875
33.979296875
32.0
30.7396484375
28.220703125
24.6171875
23.358593749999997
21.917187499999997
21.55859375
19.4
18.682812499999997
15.8
14.534375
13.099999999999998
11.665624999999999
9.3171875
8.782812499999999
8.065625
6.800000000000001
5.365624999999998
5.0
4.465624999999999
5.182812500000001
5.182812500000001
4.817187499999999
5.182812500000001
5.365624999999998
4.465624999999999
3.5656250000000007
2.6656249999999986
1.5687499999999979
0.8656249999999979
1.3999999999999986
1.2312499999999993
0.8656249999999979
0.5
-0.23125000000000284
-0.5687500000000014
-1.30000000

25.520703125
25.34140625
24.979296875
24.25859375
24.25859375
23.358593749999997
22.45859375
22.64140625
22.1
21.917187499999997
22.1
21.917187499999997
21.741406249999997
21.741406249999997
21.0171875
21.3828125
22.1
22.64140625
23.7171875
24.6171875
26.05859375
26.779296875
27.14140625
27.679296875
28.7603515625
27.85859375
29.479296875
32.359912109375
32.9
33.8
34.1603515625
30.91982421875
31.459912109375
32.540087890625
33.4396484375
34.7
35.6
36.85859375
37.4
38.65859375
39.2
41.35859375
42.44140625
43.7
41.54140625
41.0
39.74140625
38.65859375
38.120703125
37.75859375
37.220703125
37.04140625
36.14140625
32.9
30.5603515625
28.7603515625
28.220703125
26.779296875
24.25859375
23.358593749999997
21.741406249999997
21.3828125
20.65859375
20.65859375
20.299999999999997
21.55859375
22.1
21.741406249999997
21.917187499999997
22.1
19.5828125
17.7828125
17.7828125
16.7
15.8
13.8171875
12.017187499999999
9.6828125
7.517187499999999
5.899999999999999
5.0
4.099999999999998
3.3828125
2.834374

35.6
35.420703125
33.979296875
33.979296875
35.0603515625
35.6
35.420703125
35.779296875
36.14140625
37.04140625
37.579296875
38.65859375
39.3828125
40.2828125
41.0
41.54140625
42.25859375
42.0828125
42.6171875
42.6171875
41.7171875
42.25859375
42.0828125
41.9
42.0828125
42.25859375
44.05859375
42.9828125
44.6
45.5
44.7828125
44.24140625
41.9
43.8828125
45.85859375
44.95859375
47.834375
48.017187500000006
46.4
46.4
47.1171875
46.5828125
46.4
45.85859375
44.7828125
44.4171875
43.8828125
42.8
41.7171875
40.8171875
41.9
40.1
39.9171875
40.64140625
40.1
41.35859375
41.9
40.8171875
41.1828125
42.9828125
46.04140625
46.4
47.665625
49.634375000000006
45.85859375
47.834375
47.834375
46.4
45.14140625
45.14140625
44.6
43.15859375
42.8
42.44140625
40.8171875
38.65859375
38.3
36.85859375
36.679296875
37.75859375
41.9
43.15859375
44.4171875
47.834375
49.282812500000006
49.634375000000006
50.534375
51.8
52.165625000000006
52.517187500000006
51.8
47.4828125
46.934375
46.5828125
46.4
45.6828125
44.417

74.13125
73.934375
71.234375
70.165625
69.96875
66.36875
64.23125
62.965625
61.868750000000006
62.234375
60.434375
60.96875
64.934375
66.93125
68.73125
69.96875
71.6
73.934375
73.934375
75.734375
76.1
75.734375
76.634375
78.434375
77.0
76.1
74.13125
73.56875
71.43125
69.434375
68.9
69.265625
67.83125000000001
66.36875
66.734375
66.734375
69.265625
69.06875
71.76875000000001
74.834375
78.265625
80.43125
81.865625
83.30000000000001
84.2
85.26875000000001
86.9
85.1
85.465625
84.36875
83.665625
82.934375
80.234375
79.334375
78.434375
77.16875
75.2
75.36875
75.03125
71.965625
73.765625
74.30000000000001
73.934375
73.56875
75.36875
75.93125
79.7
82.03437500000001
83.834375
84.03125
84.36875
83.665625
81.865625
79.53125
77.9
76.1
73.765625
74.834375
71.6
69.80000000000001
68.0
63.865625
61.334375
61.868750000000006
65.46875
65.834375
66.734375
69.06875
70.86875
71.6
73.4
75.03125
76.1
75.734375
76.1
75.56562500000001
74.46875
71.965625
68.53437500000001
67.634375
64.23125
62.76875
60.8
57.917

69.80000000000001
70.7
70.86875
74.665625
77.53437500000001
77.365625
78.265625
78.265625
78.06875
76.83125000000001
72.5
71.06562500000001
68.73125
67.83125000000001
69.06875
66.03125
65.30000000000001
64.03437500000001
63.33125
62.065625
61.868750000000006
64.765625
66.734375
68.9
71.06562500000001
74.834375
74.834375
76.83125000000001
78.434375
78.63125
80.43125
80.6
79.53125
76.83125000000001
74.665625
74.30000000000001
70.86875
71.6
72.134375
71.43125
69.96875
66.03125
65.665625
64.765625
63.66875
64.765625
67.1
69.96875
70.53125
71.234375
74.30000000000001
72.865625
75.36875
76.634375
76.83125000000001
75.734375
76.634375
75.03125
74.13125
72.33125000000001
71.06562500000001
69.96875
65.46875
64.56875
63.865625
59.534375
60.265625
58.634375000000006
58.634375000000006
59.1828125
60.0828125
62.76875
64.4
64.934375
66.2
69.80000000000001
70.165625
68.16875
71.6
70.334375
70.334375
69.434375
65.13125
65.46875
60.6171875
59.365625
61.868750000000006
60.8
61.868750000000006
61.334375


57.2
57.3828125
58.465625
58.282812500000006
59.1828125
59.0
58.8171875
58.8171875
59.7171875
62.065625
64.56875
64.56875
65.834375
68.0
63.66875
65.834375
60.96875
58.282812500000006
56.4828125
56.834375
56.4828125
54.6828125
53.4171875
50.1828125
46.934375
45.3171875
43.34140625
41.1828125
42.8
43.5171875
45.5
48.2
51.6171875
55.034375
55.034375
55.2171875
56.4828125
58.8171875
59.1828125
59.1828125
58.282812500000006
55.5828125
51.0828125
52.7
48.9171875
48.734375
48.565625
48.565625
46.4
48.017187500000006
44.95859375
42.8
41.1828125
41.54140625
45.6828125
48.734375
51.265625
55.934375
58.282812500000006
60.434375
61.868750000000006
62.065625
60.0828125
57.565625
55.934375
55.2171875
55.400000000000006
55.5828125
55.5828125
55.5828125
55.5828125
55.400000000000006
55.5828125
55.400000000000006
53.065625
52.334375
50.534375
50.365625
49.634375000000006
51.6171875
54.3171875
55.400000000000006
54.6828125
54.6828125
54.3171875
54.6828125
52.8828125
53.065625
51.9828125
51.434375
50.90

35.420703125
32.0
30.38017578125
31.459912109375
29.3
30.7396484375
30.38017578125
29.3
30.91982421875
30.38017578125
27.320703125
25.520703125
24.8
24.25859375
24.44140625
25.34140625
26.420703125
29.6603515625
32.0
33.979296875
35.779296875
36.320703125
35.95859375
35.2396484375
34.7
34.1603515625
33.8
34.520703125
34.3396484375
33.4396484375
32.0
30.7396484375
31.640087890625
30.38017578125
30.2
30.5603515625
29.6603515625
29.6603515625
29.479296875
30.2
31.640087890625
33.4396484375
36.320703125
36.679296875
39.020703125
40.45859375
41.1828125
41.35859375
39.9171875
37.75859375
36.320703125
35.2396484375
35.0603515625
32.9
31.459912109375
29.6603515625
25.879296875
25.34140625
24.25859375
25.520703125
25.879296875
22.2828125
26.24140625
27.5
29.120703125
34.3396484375
36.14140625
37.94140625
38.120703125
39.2
40.64140625
40.2828125
40.1
40.2828125
40.2828125
40.2828125
39.55859375
40.2828125
40.1
39.2
37.04140625
38.479296875
36.85859375
36.679296875
33.979296875
33.2603515625
30.9

33.2603515625
33.2603515625
33.08017578125
32.9
33.4396484375
33.8
33.8
33.979296875
33.979296875
34.1603515625
34.520703125
34.520703125
34.3396484375
33.8
33.4396484375
33.4396484375
33.08017578125
32.9
32.71982421875
32.71982421875
32.71982421875
32.540087890625
32.71982421875
32.71982421875
32.9
33.08017578125
33.08017578125
33.4396484375
33.4396484375
33.8
33.979296875
34.3396484375
34.3396484375
33.979296875
34.1603515625
33.4396484375
33.2603515625
33.08017578125
33.08017578125
33.08017578125
32.71982421875
32.1799560546875
31.640087890625
31.1
30.7396484375
30.020703125
29.120703125
28.7603515625
28.579296875
28.9396484375
29.479296875
30.020703125
30.2
30.38017578125
30.2
31.1
31.459912109375
31.459912109375
32.359912109375
32.540087890625
32.1799560546875
33.2603515625
33.979296875
34.1603515625
35.420703125
33.979296875
33.8
33.61982421875
33.979296875
34.3396484375
33.8
33.61982421875
33.4396484375
33.4396484375
33.8
33.61982421875
34.3396484375
35.2396484375
35.779296875
3

### Addition

### Instructions
* Print Vector Addition of `temperatures` and `dew_point_temperatures`
* Print Scalar Addition of `temperatures` + 100

In [60]:
# Total temperature
a1 = temperatures + dew_point_temperatures
a2 = temperatures + 100
print(a1)
print(a2)

# Scalar Addition


[-5.7 -5.5 -5.2 ... -2.  -2.  -2.1]
[ 98.2  98.2  98.2 ...  99.5  99.8 100. ]


### Division
### Instructions
* Create an array from `1` to `10` using `np.arange()` and passing parameter as `dtype=np.float16` and reshape it in 3 X 3 matrix and save it as `array1`
* Create an array from `100` to `109` using `np.arange()` and passing parameter as `dtype=np.float16` and reshape it in 3 X 3 matrix and save it as `array2`
* Perform Vector Division by dividing `array2` by `array1`
* Perform Scalar Division by dividing `array2` by `3`

In [66]:
a1 = np.arange(1,10,dtype = np.float16)
array1 = a1.reshape(3,3)
print(array1)
a2 = np.arange(100,109, dtype = np.float16)
array2 = a2.reshape(3,3)
print(array2)
# Vector Division
print(array2/array1)
print(array2/3)
# Scalar Division


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[100. 101. 102.]
 [103. 104. 105.]
 [106. 107. 108.]]
[[100.     50.5    34.   ]
 [ 25.75   20.8    17.5  ]
 [ 15.14   13.375  12.   ]]
[[33.34 33.66 34.  ]
 [34.34 34.66 35.  ]
 [35.34 35.66 36.  ]]


## Comparison

Comparing two numpy arrays for equality, element-wise

In [86]:
a = dew_point_temperatures < -5
d = dew_point_temperatures[a]
d.shape

(2390,)

### Instructions
* Find `temperatures` that are above `0` degree celcius and save it as `greater_than_0`
* Print `temperatures` and `greater_than_0`
* Print type of `greater_than_0` using `type()`
* Print type of `greater_than_0` using `.dtype`

### Instructions
* Create 3 X 3 matrix using `1` to `9` numbers and save it as `arr`
* Check the condition for `2` or `5` in `arr` and save it as `two_or_five` and print it.

In [101]:
a = temperatures > 0 
b = temperatures < 20
print(temperatures[np.logical_and(a,b)])

[0.2 0.8 1.8 ... 0.6 0.1 0.2]


In [109]:
arr = np.arange(1,10)
arr = arr.reshape(3,3)
a = arr == 2
b = arr == 5
print(arr[np.logical_or(a,b)])

[2 5]


<img src="../images/icon/Technical-Stuff.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Aggregation 
***
* **`sum()`:** Computes the sum of all the elements in a vector, or the sum along a dimension in a matrix.
* **`mean()`:** Computes the average of all the elements in a vector, or the average along a dimension in a matrix.
* **`max()`/`min()`:** Identifies the maximum/minimum value among all the elements in a vector, or along a dimension in a matrix.
* **`argmax()`/`argmin()`:** Returns the index of maximum/minimum element.

### Instructions
* Find Max temperature using `.max()` on `temperatures`
* Find Min temperature using `.min()` on `temperatures`
* Find Mean temperature using `.mean()` on `temperatures`
* Find index of Max temperature using `.argmax()` on `temperatures`
* Find index of Min temperature using `.argmin()` on `temperatures`

In [117]:
# Find max, min, mean temperature

max = temperatures.max()
print(max)

min = temperatures.min()
print(min)

mean = temperatures.mean()
print(mean)

maxi = np.argmax(temperatures)
print(maxi)

mini = np.argmin(temperatures)
print(mini)

a = dew_point_temperatures[maxi]
print(a)
print(weathers[maxi])






33.0
-23.3
8.8
4143
344
19.0
[b'2012-06-21 15:00:00' b'33.0' b'19.0' b'44' b'24' b'24.1' b'100.2']
